config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :feedbacks
  resources :teams
  resources :eventslots
  resources :eventschedules
  resources :events
  resources :messages do 
    resources :comments
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/viewallevents', :to=> 'pages#viewAllEvents'
  get '/viewfeedback', :to=> 'pages#viewFeedback'
  get '/viewqueries', :to=> 'pages#viewQueries'
  get 'register/:string' => 'teams#new', as: :register_event
  get '/vieweventschedule', :to=> 'pages#viewEventSchedule'
  get 'askQuery', :to => 'queries#index'
  get '/vieweventslots/:event_schedule_id', :to=> 'pages#viewEventSlots', as: :vieweventslot
  get 'eventslot/:event_schedule_id' => 'eventslots#new', as: :event_slot_new
  get 'giveFeedback', :to => "feedbacks#new"
  get 'noticeBoard', :to=> "messages#index"
  # get '/respondquery', :to=> 'queries#respondQuery'
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy]

	def index
		@messages = Message.all.order("created_at DESC")
	end

	def show
	end

	def new
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to noticeBoard_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to noticeBoard_path
	end

	private
		def message_params
			params.require(:message).permit(:title, :description)
		end

		def find_message
			@message = Message.find(params[:id])
		end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>New Message</title>
</head>
<body>
	<div class="cont">
		<div id="contact">
			<%= simple_form_for @message do |f| %>
				<%= f.input :title, label: "Message Title" %>
				<%= f.input :description %>
				<%= f.button :submit, :style => "cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;"%>
			<% end %>
		</div>
	</div>
</body>
</html>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "View Message", message, class: "btn-custom" %>
		</div>
	</div>
<% end %>
</div>
</br>
<div class='container' id='link'>
<%= link_to 'Post a message', new_message_path %>
</div>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1 class="new-msg-header">New Message</h1>
	<%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-desc"><%= @message.description %></p>

		<h3 class="comment-section-header">Comments:</h3>

		<p><%= render @message.comments %></p>

		<h3 class="reply-to-msg">Reply to Message:</h3>

		<%= render 'comments/form' %>


		<div class="links btn-group">
			<%= link_to "Back", noticeBoard_path, class: "btn btn-default" %>
			<% if @message.user_id == current_user.id %>
				<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
			<% end %>
			<% if (@message.user_id == current_user.id || current_user.adminflag==1) %>
				<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
			<% end %>
			
		</div>
	</div>
</div>