config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :feedbacks
  resources :teams
  resources :eventslots
  resources :eventschedules
  resources :events
  resources :messages do 
    resources :comments
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/viewallevents', :to=> 'pages#viewAllEvents'
  get '/viewfeedback', :to=> 'pages#viewFeedback'
  get '/viewqueries', :to=> 'pages#viewQueries'
  get 'register/:string' => 'teams#new', as: :register_event
  get '/vieweventschedule', :to=> 'pages#viewEventSchedule'
  get 'askQuery', :to => 'queries#index'
  get '/vieweventslots/:event_schedule_id', :to=> 'pages#viewEventSlots', as: :vieweventslot
  get 'eventslot/:event_schedule_id' => 'eventslots#new', as: :event_slot_new
  get 'giveFeedback', :to => "feedbacks#new"
  get 'noticeBoard', :to=> "messages#index"
  # get '/respondquery', :to=> 'queries#respondQuery'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]

	def create
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
	end

	private

		def comment_params
			params.require(:comment).permit(:content)
		end

		def find_message
			@message = Message.find(params[:message_id])
		end

		def find_comment
			@comment = @message.comments.find(params[:id])
		end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if comment.user_id == current_user.id %>
			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
		<% end %>
		<% if (comment.user_id == current_user.id || current_user.adminflag==1) %>
			<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit %>
<% end %>