config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :feedbacks
  resources :teams
  resources :eventslots
  resources :eventschedules
  resources :events
  resources :messages do 
    resources :comments
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/viewallevents', :to=> 'pages#viewAllEvents'
  get '/viewfeedback', :to=> 'pages#viewFeedback'
  get '/viewqueries', :to=> 'pages#viewQueries'
  get 'register/:string' => 'teams#new', as: :register_event
  get '/vieweventschedule', :to=> 'pages#viewEventSchedule'
  get 'askQuery', :to => 'queries#index'
  get '/vieweventslots/:event_schedule_id', :to=> 'pages#viewEventSlots', as: :vieweventslot
  get 'eventslot/:event_schedule_id' => 'eventslots#new', as: :event_slot_new
  get 'giveFeedback', :to => "feedbacks#new"
  get 'noticeBoard', :to=> "messages#index"
  # get '/respondquery', :to=> 'queries#respondQuery'
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	validates_presence_of :eventname
	validates_presence_of :feedback
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to root_path, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:eventname,:feedback)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Feedback</title>
</head>
<body>
	<%= simple_form_for @feedback do |f| %>
	<div class="cont">
	<%= f.error_notification %>  
		<div class="form-inputs" id="contact">
		   <%= f.label :Event_name, :required => true%>
		   <%= collection_select(:feedback,:eventname, Event.all,:name,:name,{prompt: true}) %>
		   <%= f.input :feedback, required: true %>
		   <%= f.button :submit, :style => "cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;"%>
		</div>
	<% end %>
	</div>
</body>
</html>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<div class="col-md-8 col-md-offset-2">
<h1 class="new-msg-header">New Feedback</h1>
<%= render 'form', feedback: @feedback %>
</div>
<div>
<%= link_to 'Back', :back %>
</div>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>