config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :feedbacks
  resources :teams
  resources :eventslots
  resources :eventschedules
  resources :events
  resources :messages do 
    resources :comments
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/viewallevents', :to=> 'pages#viewAllEvents'
  get '/viewfeedback', :to=> 'pages#viewFeedback'
  get '/viewqueries', :to=> 'pages#viewQueries'
  get 'register/:string' => 'teams#new', as: :register_event
  get '/vieweventschedule', :to=> 'pages#viewEventSchedule'
  get 'askQuery', :to => 'queries#index'
  get '/vieweventslots/:event_schedule_id', :to=> 'pages#viewEventSlots', as: :vieweventslot
  get 'eventslot/:event_schedule_id' => 'eventslots#new', as: :event_slot_new
  get 'giveFeedback', :to => "feedbacks#new"
  get 'noticeBoard', :to=> "messages#index"
  # get '/respondquery', :to=> 'queries#respondQuery'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :eventschedules
  has_many :teams
  validates_presence_of :name
  validates_presence_of :duration, numericality: true
  validates_presence_of :teamsize, numericality: true, greater_than_or_equal_to: 1 
  validates_presence_of :maxnumberofteams, numericality: true, greater_than_or_equal_to: 1 
end

app/models/eventschedule.rb
class GoodnessValidator < ActiveModel::Validator
  def validate(record)
    if record.starttime.strftime( "%H%M" ) >= record.endtime.strftime( "%H%M" )
      record.errors[:base] << "Start Time should be smaller than End Time"
    end
  end
end

class Eventschedule < ApplicationRecord
  belongs_to :event
  has_many :eventslots
  # validates_presence_of :name
  validates_presence_of :date
  validates_presence_of :starttime
  validates_presence_of :endtime
  validates_with GoodnessValidator
end

app/models/eventslot.rb
class GoodnessValidator < ActiveModel::Validator
  def validate(record)
    if record.starttime.strftime( "%H%M" ) >= record.endtime.strftime( "%H%M" )
      record.errors[:base] << "Start Time should be smaller than End Time"
    end
    if record.team1name == record.team2name
      record.errors[:base] << "Team Names should be different"
    end
  end
end

class Eventslot < ApplicationRecord
  belongs_to :eventschedule
  validates_presence_of :team1name
  validates_presence_of :team2name
  validates_presence_of :starttime
  validates_presence_of :endtime
  validates_presence_of :venue
	validates_with GoodnessValidator
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	validates_presence_of :eventname
	validates_presence_of :feedback
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/query.rb
class Query < ApplicationRecord
  belongs_to :user
  validates_presence_of :question
  # validates_presence_of :answer
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates_presence_of :teamname
  validates_uniqueness_of :teamname
  validates_presence_of :member1,:member2
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :teams
  has_many :queries
  has_many :messages
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!
  def home
		if current_user.present? && current_user.adminflag==1 then
			render 'pages/adminindex'
		else
			render 'pages/index'
		end
  end

  def viewAllEvents
  	if current_user.present? then
  		@events_grid = initialize_grid(Event.all)
      # @events = Event.all
      render 'pages/viewallevents'
    else
  		render 'pages/index'
		end
  end

  def viewFeedback
    if current_user.present? && current_user.adminflag==1 then
  		@feedbacks_grid = initialize_grid(Feedback.all)
      # @events = Event.all
      render 'pages/viewfeedback'
    else
  		render 'pages/index'
		end
  end

  def viewQueries
    if current_user.present? && current_user.adminflag==1 then
  		@queries_grid = initialize_grid(Query.all)
      # @events = Event.all
      render 'pages/viewqueries'
    else
  		render 'pages/index'
		end
  end

  def viewEventSchedule
    if current_user.present?  then
      @eventschedule_grid = initialize_grid(Eventschedule.all)
      # @events = Event.all
      render 'pages/vieweventschedule'
    else
      render 'pages/index'
    end
  end

  def viewEventSlots
      @eventslot_grid = initialize_grid(Eventslot.where(eventschedule_id: pages_params[:event_schedule_id]))
      render 'pages/vieweventslots'
  end


  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def pages_params
      # params.require(:feedback).permit(:event_name,:feedback)
      params.permit(:event_schedule_id)
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.where(:user_id => current_user.id)
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create   
    @team=Team.new(team_params) 
    #respond_to do |format|
      if @team.save
        @event=Event.find(team_params[:event_id])
        @event.update_attribute(:numberofteams , @event.numberofteams+1)
        @event.save
        #format.html { redirect_to @team, notice: 'Team was successfully created.' }
        #format.json { render :show, status: :created, location: @team }
         redirect_to @team, notice: 'Team was successfully created.'
      else
        @event=Event.find(team_params[:event_id])
        #format.html { render :new }
        #format.json { render json: @team.errors, status: :unprocessable_entity }
        redirect_to register_event_url(@event.name), notice: 'Error Encountered.'
      end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:event_id,:user_id,:teamname,:member1,:member2,:member3,:member4,:member5,:member6,:member7,:member8,:member9,:member10,:member11)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
  content_for(:header) { text.to_s }
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/eventslots_helper.rb
module EventslotsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sports Event Management Portal</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "default" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="
    font-family: 'RobotoDraft', 'Roboto', sans-serif;
    font-size: 14px;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;">

  <div id="header">
  <div id="menu" class="container">
    <ul style="float: right;">
      <li><a href="/" accesskey="1" title="">Homepage</a></li>
      <% if user_signed_in? %>
            <% if current_user.adminflag==1 %>
              <li><a href="/noticeBoard" accesskey="1" title="">Notice Board</a></li>
            <% end %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu current_page_item" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'View Schedule', eventschedules_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
    </ul>
  </div>
</div>
 <!--    <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to '', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'View Schedule', eventschedules_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
</nav> -->

    <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <% end %>
    </div>

    <%= yield :top_content %>
    <div class="container">
        <h1><%= yield :header %></h1>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/adminindex2.html.erb
<!DOCTYPE html>
<html>
<title>Sports Management Portal</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3-theme-indigo.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>

<!-- Header -->
<header class="w3-container w3-theme w3-padding" id="myHeader">
  <div class="w3-center">
  <h1 class="w3-xxxlarge w3-animate-bottom">Welcome Admin</h1>
  </div>
</header>


<div class="w3-row-padding w3-center w3-margin-top">
  <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <div class="w3-center">
        <a href="/events/new">
        <div id="file-img">
          
        </div>
      </a>
    </div>
    <h4>Create New Event</h4><br>
    </div>
  </div>

  <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <a href="/viewallevents">
        <div id="p-img">
          
        </div>
      </a>
      <h4>View all event</h4><br>
    </div>
  </div>

    <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <a href="/viewfeedback">
        <div id="own-img">
          
        </div>
      </a>
      <h4>View Feedback</h4><br>
    </div>
  </div>  
</div>

<div class="w3-row-padding w3-center w3-margin-top">
  <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <div class="w3-center">
        <a href="/viewqueries">
        <div id="license-img">
        
        </div>
      </a>
    </div>
    <h4>View Queries</h4><br>
    </div>
  </div>

  <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <a href="/eventschedules/new">
        <div id="own-img">
          
        </div>
      </a>
      <h4>Add Schedules</h4><br>
    </div>
  </div>  

   <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <a href="/vieweventschedule">
        <div id="own-img">
          
        </div>
      </a>
      <h4>View Schedules</h4><br>
    </div>
  </div> 

  <div class="w3-third">
    <div class="w3-card-8 w3-padding-top" style="min-height:400px">
      <a href="/noticeBoard">
        <div id="own-img">
          
        </div>
      </a>
      <h4>Notice Board</h4><br>
    </div>
  </div>  

</div>

</div>
</body>
</html>

app/views/pages/respondquery.html.erb
<%= form_tag(controller: "queries", action: "update", method: "put") %>
<%= submit_tag("Search") %>
<% end %>

app/views/pages/viewallevents.html.erb
<div>
		<%= grid(@events_grid) do |g|
			# g.column name: 'ID' do |validation|
			# 	validation.id
			# end
			g.column  name: 'Name' do |event|
				event.name
			end
			g.column name: 'Duration (in hours)' do |event|
				event.duration
			end

			if current_user.adminflag==0 then
     		 g.column name: 'Teamsize' do |event|
				event.teamsize
				end
			end	
			if current_user.adminflag==0 then
     		 g.column name: 'Schedule' do |event|
				link_to 'View schedule', vieweventschedule_path
				end
			end	
			if current_user.adminflag==1 then
     		 g.column name: 'Interested Attendees' do |event|
				event.expectedNoOfAttendees
				end
			end	
			# g.column name: 'Proposal' do |owned|
		  #       link_to 'Proposal Document', owned.avatar.url, :target => "_blank"
      #
			# end
			if current_user.adminflag==1 then
				g.column name: 'Edit Event' do |event|
	    		link_to 'Edit',edit_event_path(event)
	    	end
  		end
		end-%>
</div>
<% if  current_user.adminflag==0 %>
<%= link_to 'Back', events_path %>
<% else %>
<%= link_to 'Back', root_path %>
<% end %>

app/views/pages/vieweventschedule.html.erb
<div>
		<%= grid(@eventschedule_grid) do |g|
			g.column  name: 'Event Name' do |eventschedule|
				eventschedule.event.name
			end
			g.column name: 'Date' do |eventschedule|
				eventschedule.date
			end
			g.column name: 'Start Time' do |eventschedule|
				eventschedule.starttime.strftime('%r')
			end
      g.column name: 'End Time' do |eventschedule|
				eventschedule.endtime.strftime('%r')
			end
			if current_user.adminflag==1 then
		g.column name: 'Edit Event Schedule' do |eventschedule|
    		link_to 'Edit', edit_eventschedule_path(eventschedule)
  		end
  	end
  	if current_user.adminflag==1 then
			g.column name: 'Create Event Slot' do |eventschedule|
    		link_to 'Click to Create', event_slot_new_path(eventschedule)
  		end
  	end
			g.column name: 'View Event Slots' do |eventschedule|
    		link_to 'Click to Open', vieweventslot_path(eventschedule)
  		end
		end-%>
</div>
<% if  current_user.adminflag==0 %>
<%= link_to 'Back', viewallevents_path %>
<% else %>
<%= link_to 'Back', root_path %>
<% end %>

app/views/pages/vieweventslots.html.erb
<div>
<%= grid(@eventslot_grid) do |g|
  g.column  name: 'Team 1' do |eventslot|
    eventslot.team1name
  end
  g.column name: 'Team 2' do |eventslot|
    eventslot.team2name
  end
  g.column name: 'Start Time' do |eventslot|
    eventslot.starttime.strftime('%r')
  end
  g.column name: 'End Time' do |eventslot|
    eventslot.endtime.strftime('%r')
  end
  if current_user.present? && current_user.adminflag==1 then
    g.column name: 'Edit Event Slot' do |eventslot|
      link_to 'Edit',edit_eventslot_path(eventslot)
    end
  end
  g.column name: 'Winner' do |eventslot|
    if eventslot.winner == "" || eventslot.winner.nil?
      "Yet to be Decided"
    else
      eventslot.winner
    end
  end
  # g.column name: 'View Event Slots' do |eventslot|
  #   link_to 'Click to Open', vieweventslots_path(eventslot)
  # end
end-%>
</div>

<%= link_to 'Back', vieweventschedule_path %>

app/views/pages/viewfeedback.html.erb
<div>
		<%= grid(@feedbacks_grid) do |g|
			g.column  name: 'Event name' do |feedback|
				feedback.eventname
			end

      g.column  name: 'Feedback' do |feedback|
				feedback.feedback
			end

    end-%>
</div>
<%= link_to 'Back', root_path %>

app/views/pages/viewqueries.html.erb
<div>
		<%= grid(@queries_grid) do |g|
			g.column  name: 'Query' do |query|
				query.question
			end

			g.column  name: 'Answer' do |query|
				if query.answer.nil?
					"Not Answered"
				else
					query.answer
				end
			end

      g.column  name: 'Respond' do |query|
				link_to 'Respond', edit_query_path(query)
			end

    end-%>
</div>
<%= link_to 'Back', root_path %>